### PR TITLE
cpog format files added

### PR DESCRIPTION
**Pull request by allegroCoder**
`cpog` format files added into the repository.

### CODE REVIEW

**Comment by allegroCoder** [comment]
@snowleopard Further to our offline discussion, I have added the files in the text format.

**Comment by snowleopard** [comment]
@allegroCoder Great! I noticed there are also some `.work` files in the commit -- why?

**Comment by allegroCoder** [comment]
It is because I have added the names of some graphs which were unlabelled before.

**Comment by snowleopard** [comment]
I see! Merged now.

**Pull request merged**
