### PR TITLE
New processor benchmarks

### PR DESCRIPTION
**Pull request by allegroCoder**

### CODE REVIEW

**Comment by snowleopard** [comment]
Thanks! But I think we should also update the benchmark table here: 

https://github.com/tuura/graph-families/tree/master/real/processors

**Comment by allegroCoder** [comment]
Sure, I will make a new PR with the updated benchmarks ASAP

**Comment by snowleopard** [comment]
Thanks! One question about the naming you use: does `Intel_8051_6.work` mean there are 6 graphs?

**Comment by allegroCoder** [comment]
Yes!

**Comment by snowleopard** [comment]
:+1:

**Comment by allegroCoder** [comment]
Table updated! Maybe you want to merge now, I will make a separate PR when I will have all the Max's graphs modelled!

**Comment by snowleopard** [comment]
Looks good, thanks! Merged now.

**Pull request merged**
