### PR TITLE
More benchmarks for Intel-8051

### PR DESCRIPTION
**Pull request by allegroCoder**
Benchmarks for Asynch-8051(Top-level control) processor: `[5,10..35] : 37`graphs.

### CODE REVIEW

**Comment by snowleopard** [comment]
Thanks @allegroCoder! A couple of questions:
- Why do we have two separate Intel 8051 subtables?
- You have seconds in brackets, but I think we put opcode length in brackets.

**Comment by allegroCoder** [comment]
> Why do we have two separate Intel 8051 subtables?

That's a good point! There is an overlapping between some of the graphs present in `Intel-8051` and `Asynch-8051`. What about creating two folders inside `Intel-8051` named: `subset-1` and `subset-2`?

@Edit: Maybe a better idea would be simply concatenating the two subsets. All the previous Intel graphs, along with the ones I have just done (starting from the file composed by 10 graphs). Yes, I will probably do that. Let me know your thoughts about this.

Or maybe, do you want me to mix all the graphs together in the same folder?

> You have seconds in brackets, but I think we put opcode length in brackets.

Sorry, that was misleading. The numbers I inserted between the brackets represent the number of solutions tried in `scenco`. Is it ok for you if I recompute all of the solutions for heuristic encoding for all of the graphs, setting the number of solutions to 10? In such a way to have more consistent results in terms of run-time?

**Comment by allegroCoder** [comment]
Now, It should be ready to be merged in my opinion. @snowleopard : Please, have a look at the tables and at the repository tree to be sure.

I have:
- merged the previous Intel-8051 graphs with the other ones that I have modelled. 
- tuned the benchmarks of the `heuristic encoding`, computing the final result using 10 solutions.
- added "(bits)" close to "Area" inside the table in the `README` file

**Comment by snowleopard** [comment]
:+1:

**Pull request merged**
